from enum import StrEnum, auto

__all__ = ('CallbackDataPrefix',)


class CallbackDataPrefix(StrEnum):
    PERFORMER_REGISTER = auto()
    CAR_WASH_DETAIL = auto()
    CAR_WASH_LIST = auto()
    CAR_WASH_CREATE = auto()
    CAR_WASH_CREATE_CONFIRM = auto()
    CAR_WASH_UPDATE = auto()
    CAR_WASH_UPDATE_CONFIRM = auto()
    CAR_WASH_DELETE_CONFIRM = auto()
    STAFF_DETAIL = auto()
    STAFF_UPDATE = auto()
    STAFF_LIST = auto()
    STAFF_REGISTER_REJECT = auto()
    STAFF_REGISTER_ACCEPT = auto()
    SHIFT_OWN = auto()
    SHIFT_CREATE = auto()
    STAFF_MENU = auto()
    CAR_CLASS = auto()
    SHIFT_WORK_TYPE = auto()
    CAR_NUMBER = auto()
    WINDSHIELD_WASHER_REFILLED = auto()
    WINDSHIELD_WASHER_REFILLED_VALUE = auto()
    ADDITIONAL_SERVICES_INCLUDED = auto()
    ADD_CAR_CONFIRM = auto()
    WASH_TYPE = auto()
    SHIFT_START_REQUEST_REJECT = auto()
    SHIFT_START_REQUEST_ACCEPT = auto()
    PENALTY_CREATE_CHOOSE_STAFF = auto()
    PENALTY_CREATE_CHOOSE_REASON = auto()
    PENALTY_CREATE_ACCEPT = auto()
    PENALTY_CREATE_REJECT = auto()
    SURCHARGE_CREATE_CHOOSE_STAFF = auto()
    SURCHARGE_CREATE_ACCEPT = auto()
    SURCHARGE_CREATE_REJECT = auto()
    MAILING = auto()
    MAILING_CREATE_ACCEPT = auto()
    MAILING_CREATE_REJECT = auto()
