from enum import StrEnum

__all__ = ('ButtonText',)


class ButtonText(StrEnum):
    STAFF_LIST = '👥 Список всех сотрудников'
    SHIFTS = '📅 Графики'
    SHIFTS_TODAY = '📅 Сегодня в смене'
    CAR_WASH_LIST = '🚿 Меню моек'
    PENALTY = '🛑 Оштрафовать'
    SURCHARGE = '💰 Доплатить'
    SHIFT_CARS_COUNT_BY_STAFF = '📊 Кто сколько'
    SHIFT_CARS_WITHOUT_WINDSHIELD_WASHER = '💧 Недоливы'
    MAILING = '📩 Рассылка'
    SHIFT_START = '🚀 Начать смену'
    SHIFT_START_EXTRA = '🚀 Начать доп.смену'
    SHIFT_SCHEDULE = '📅 График работы'
    REPORT_FOR_PERIOD = '📊 Отчет за период'
    SHIFT_ADD_CAR = '🚗 Добавить автомобиль'
    SHIFT_ADDITIONAL_SERVICES = '🔧 Отметить доп.услуги'
    SHIFT_ADDED_CARS = '🚗 Добавленные автомобили'
    SHIFT_CHANGE_CAR_WASH = '🫧 Поменять мойку'
    SHIFT_END = '🛑 Завершить смену'
    ATTACH_REPLY_MARKUP = '⌨ Привязать кнопки'
    SKIP = '➡ Пропустить'
    MAILING_STAFF = '👥 Выбрать сотрудников'
    REGISTER = '🚀 Зарегистрироваться'
    MAIN_MENU = '📲 Главное меню'
    SCHEDULE_SELF = '📆 Мой график'
    CAR_ADDITIONAL_SERVICES = '🔧 Отметить доп.услуги авто'
    LATER = '➡ Сделаю это позже'
    SHIFT_APPLY = '✏️ Записаться на смены'
    SHIFT_SCHEDULE_MONTH_CALENDAR = '📅 Выбрать даты рабочих смен'
    EXTRA_SHIFT_CALENDAR = '📆 Выбрать дату на доп.смену'
    OTHER = '📱 Другое'
